config/routes.rb
Rails.application.routes.draw do

  root "cocktails#index"

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :cocktails, only: [:index, :show, :new, :create, :destroy] do
    resources :doses, only: [:new, :create, :destroy]
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
  end

  mount Attachinary::Engine => "/attachinary"

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :cocktails, dependent: :destroy
end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  has_many :doses, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :ingredients, through: :doses
  belongs_to :category
  belongs_to :user

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :category_id, presence: true
  validates :description, presence: true
end

app/models/dose.rb
class Dose < ActiveRecord::Base
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail_id, presence: true
  validates :ingredient_id, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :doses, dependent: :destroy
  has_many :cocktails, through: :doses

  validates :name, presence: true
  validates :name, uniqueness: true

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :cocktail
  belongs_to :user

  validates :content, presence: true
  validates :rating, presence: true
  validates :cocktail_id, presence: true
  validates :user_id, presence: true
  validates :cocktail_id, uniqueness: { scope: :user_id }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :cocktails, dependent: :destroy
  has_many :reviews, dependent: :destroy

  has_secure_password
  has_attachment  :avatar, accept: [:jpg, :png, :gif], maximum: 4

  validates :avatar, presence: true

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    if (session[:user_id] && !(User.all.map(&:id).find(session[:user_id])))
      session[:user_id] = nil
    end
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def user_signed_in?
    !current_user.nil?
  end
  helper_method :user_signed_in?

  def restrict_access
    unless user_signed_in?
      render html: "<strong>Not Found</strong>".html_safe
    end
  end

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]
  before_action :restrict_access, only: [:new, :create]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @review = @cocktail.reviews.new()
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = current_user.cocktails.new(params_cocktail)
    if @cocktail.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  # def update
  #   @cocktail.update(params_cocktail)
  # end

  # def edit
  # end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def params_cocktail
    params.require(:cocktail).permit(:name, :description, :category_id)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create]
  before_action :set_dose, only: [:destroy]
  before_action :check_author, only: [:new, :create, :destroy]

  def new
    @dose = @cocktail.doses.new
  end

  def create
    @dose = @cocktail.doses.new(dose_params)
    if @dose.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def destroy
    @dose.destroy
    redirect_to '/'
  end

private
  def dose_params
    params.require(:dose).permit(:cocktail_id, :ingredient_id, :description)
  end

  def set_dose
    @dose = Dose.find(params[:id])
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def check_author
    unless current_user == @cocktail.user
      render html: "<strong>Not Found</strong>".html_safe
    end
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  before_action :et_cingredient, only: [:show, :edit, :update, :destroy]
  before_action :restrict_access, only: [:new, :create]

  def index
    @ingredients = Ingredient.all
  end

  def show
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = current_user.ingredients.new(arams_cingredient)
    if @ingredient.save
      redirect_to @ingredient
    else
      render :new
    end
  end

  # def update
  #   @ingredient.update(params_ingredient)
  # end

  # def edit
  # end

  def destroy
    @ingredient.destroy
    redirect_to ingredients_path
  end

private

  def et_cingredient
    @ingredient = Ingredient.find(params[:id])
  end

  def arams_cingredient
    params.require(:ingredient).permit(:name, :description, :category_id)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_cocktail, only: [:edit, :update, :new, :create]
  before_action :set_review, only: [:edit, :update, :destroy]
  before_action :check_author, only: [:edit, :update, :destroy]

  def new
    @review = @cocktail.reviews.new
  end

  def create
    @review = @cocktail.reviews.new(reviews_params)
    if @review.save
      redirect_to @cocktail
    else
      render "cocktails/show"
    end
  end

  def edit
  end

  def update
    @review.update(reviews_params)
    redirect_to @cocktail
  end

  def destroy
    @review.destroy
    redirect_to '/'
  end

private
  def reviews_params
    params[:review][:user_id] = current_user.id
    params.require(:review).permit(:cocktail_id, :user_id, :content, :rating)
  end

  def set_review
    @review = Review.find(params[:id])
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def check_author
    unless current_user == @review.user
      raise ActionController::RoutingError.new("You're not allowed here.")
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :avatar, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_card.html.erb
<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= locals[:image] -%>');">
  <div class="card-category"><%= locals[:category] -%></div>
  <div class="card-description">
    <h2><%= locals[:title] -%></h2>
    <p><%= locals[:description] -%></p>
  </div>
  <a class="card-link" href="<%= locals[:url] -%>" ></a>
</div>

app/views/application/_footer.html.erb
<div class="footer"></div>

app/views/application/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "cockrail.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <%= link_to t(".top_call_to_action", default: "New Cocktail"), new_cocktail_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
      <%= link_to t(".sign_out", default: "Log out"), logout_path, class: "navbar-wagon-item navbar-wagon-button btn"%>

    <% else %>
      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), login_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
      <%= link_to t(".sign_up", default: "Sign up"), signup_path, class: "navbar-wagon-item navbar-wagon-button btn" %>

    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
          <li><%= link_to t(".top_call_to_action", default: "New Cocktail"), new_cocktail_path %></li>
          <li><%= link_to t(".sign_out", default: "Log out"), logout_path%></li>
        <% else %>
          <li><%= link_to t(".sign_in", default: "Login"), login_path %></li>
          <li><%= link_to t(".sign_up", default: "Sign up"), signup_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/cocktails/_review.html.erb
<div class="col-sm-6 col-md-4">
  <div class="review">
    <div class="author">
      <%= cl_image_tag(locals[:review].user.avatar.path, { size: '40x40', crop: :thumb, radius: :max, gravity: :face}) %>
      <span class="username"><%= locals[:review].user.name.capitalize %></span>
    </div>
    <div class="review-content">
      <%= locals[:review].content %>
    </div>
    <div class="rating">
      <% (locals[:review].rating).times do %>
        <%= icon("star") -%>
      <% end %>
      <% (5-locals[:review].rating).times do %>
        <%= icon("star-o") -%>
      <% end %>
    </div>
    <% if user_signed_in? && locals[:review].user == current_user %>
      <%= link_to icon('pencil-square-o'), edit_cocktail_review_path(locals[:review].cocktail, Review.where(user_id: locals[:review].user.id, cocktail_id: @cocktail.id).first), class: "show-link show-link-right" %>
    <% end %>
  </div>
</div>

app/views/cocktails/_review_form.html.erb
<div class="col-sm-6 col-md-4">
  <div class="review">
  <%= simple_form_for [locals[:review].cocktail, locals[:review]] do |f| %>
    <div class="author">
      <%= cl_image_tag(current_user.avatar.path, { size: '40x40', crop: :thumb, radius: :max, gravity: :face}) %>
      <span class="username"><%= current_user.name.capitalize %></span>
    </div>
    <div class="review-content">
      <%= f.input :content, type: "textarea", input_html: { class: "input-content", rows: 2 }, label: false, placeholder: "Leave a review?", error: false %>
    </div>
    <div class="input-rating">
    <%= f.input :rating,  as: :radio_buttons, label: false, error: false do%>
      <%= f.collection_radio_buttons :rating, (0..4).reverse_each, :succ, ->(a){false}, item_wrapper_tag: false do |b| %>
        <%= b.radio_button class: 'with-font' %>
        <%= b.label {""} %>
      <% end %>
    <% end %>
    </div>
    <%= f.button :button, class: "input-validate btn btn-primary ladda-button", "data-style": "contract" do %>
      <span class="ladda-label">Submit</span>
    <% end %>
  <% end %>
  </div>
</div>

app/views/cocktails/index.html.erb
<div class="cocktails">
  <div class="container">
    <div class="row">
      <div class="col">
        <div class="title"><h1>Cocktails</h1></div>
      </div>
    </div>
    <div class="row">
      <% @cocktails.each do |cocktail| %>
        <div class="col-md-6">
          <%= render "card", :locals => {
                                          url: cocktail_path(cocktail),
                                          image: image_url('category/'+cocktail.category.name.downcase+'.jpg'),
                                          title: cocktail.name.capitalize,
                                          category: cocktail.category.name.capitalize,
                                          description: cocktail.description.capitalize
                                        } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<%= simple_form_for @cocktail do |f| %>
  <%= f.error_notification %>

  <%= f.input :name, label: 'Name', error: 'You should provide a name.' %>
  <%= f.input :category_id, collection: Category.all ,label_method: :name, value_method: :id,label: "Category" ,include_blank: false %>
  <%= f.input :description, label: 'Description', error: 'You should provide a description.' %>
  <%= f.button :submit %>
<% end %>

app/views/cocktails/show.html.erb
<% content_for :title do %>
  <%= @cocktail.name.capitalize %>
<% end %>


<div style="padding:0 15px">
<div class="row">
  <div class="col">
    <div id="nolink" style="position: relative">
    <%= render "card", :locals => {
                                url: cocktail_path(@cocktail),
                                image: image_url('category/'+@cocktail.category.name.downcase+'.jpg'),
                                title: @cocktail.name.capitalize,
                                category: @cocktail.category.name,
                                description: @cocktail.description.capitalize
                              } %>
    <%= link_to "Back", "/", class: "back-link" %>
    </div>
    </div>
  </div>
</div>

<div class="doses">
  <% if user_signed_in? && current_user == @cocktail.user %>
      <%= link_to new_cocktail_dose_path(@cocktail), class: "show-link show-link-right" do %>
        Add an ingredient <%= icon 'plus-square-o', style: "font-size: 14px" %>
      <% end %>
      <%= link_to @cocktail, method: :delete, class: "show-link show-link-left" do%>
        Delete cocktail <%= icon 'times-circle-o', style: "font-size: 14px" %>
      <% end %>
  <% end %>
  <% @cocktail.doses.each do |dose| %>
    <div class="dose"><%= dose.description.capitalize %> of <%= dose.ingredient.name %></div>
    <div class="line"></div>
  <% end %>
</div>

<div class="reviews">
  <div class="row">
    <% @cocktail.reviews.each do |review| %>
      <% if review.content && review.content != "" %>
        <%= render "cocktails/review", locals: { review: review } %>
      <% end %>
    <% end %>
    <% if user_signed_in? %>
      <% if (@cocktail.reviews.find { |r| r.user == current_user && r.content && r.content != "" }.nil?) %>
        <%= render "cocktails/review_form", locals: { review: @review } %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/doses/new.html.erb
<h2><%= @cocktail.name %></h2>
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.error_notification %>
  <%= f.input :description, label: 'Description' %>
  <%= f.input :ingredient_id, collection: Ingredient.all, label_method: :name, value_method: :id, label: "Ingredient", include_blank: false %>
  <%= f.button :submit %>
<% end %>

app/views/reviews/_form.html.erb
<h2><%= @cocktail.name %></h2>
<%= simple_form_for [@cocktail, @review] do |f| %>
  <%= f.error_notification %>
  <%= f.input :content, label: 'Content' %>
  <%= f.input :rating, label: 'Rating', input_html: { min: '0', max: '5'} %>
  <%= f.button :submit %>
<% end %>

app/views/reviews/edit.html.erb
<%= render "form" %>

app/views/reviews/new.html.erb
<%= render "form" %>

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= simple_form_for @user do |f| %>

  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :avatar, as: :attachinary %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>